services:
  m-ui:
    image: ghcr.io/aethersailor/m-ui:latest
    container_name: m-ui
    network_mode: host
    restart: always
    environment:
      TZ: Asia/Shanghai
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    volumes:
      - /opt/m-ui/data:/data
