services:
  m-ui:
    image: ghcr.io/aethersailor/m-ui:latest
    container_name: m-ui
    network_mode: host
    restart: always
    environment:
      TZ: Asia/Shanghai
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    volumes:
      - m-ui-etc:/data/etc/m-ui
      - mihomo-etc:/data/etc/mihomo
      - m-ui-data:/data/var/lib/m-ui
      - mihomo-data:/data/var/lib/mihomo

volumes:
  m-ui-etc:
  mihomo-etc:
  m-ui-data:
  mihomo-data:
