permit nopass m-ui as root cmd /sbin/rc-service args mihomo start
permit nopass m-ui as root cmd /sbin/rc-service args mihomo stop
permit nopass m-ui as root cmd /sbin/rc-service args mihomo restart
permit nopass m-ui as root cmd /sbin/rc-service args mihomo reload
permit nopass m-ui as root cmd /sbin/rc-service args mihomo status
